# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chassis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chassis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchassis.proto\x12\x07\x63hassis\"\x07\n\x05\x45mpty\"D\n\x0cTradeRequest\x12\x12\n\ntoken_mint\x18\x01 \x01(\t\x12\x12\n\namount_sol\x18\x02 \x01(\x01\x12\x0c\n\x04side\x18\x03 \x01(\t\"J\n\rTradeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tsignature\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"[\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntry_price\x18\x02 \x01(\x01\x12\x15\n\rcurrent_price\x18\x03 \x01(\x01\x12\x13\n\x0bpnl_percent\x18\x04 \x01(\x01\"9\n\x11PositionsResponse\x12$\n\tpositions\x18\x01 \x03(\x0b\x32\x11.chassis.Position\"\"\n\x0c\x41uditRequest\x12\x12\n\ntoken_mint\x18\x01 \x01(\t\"F\n\rAuditResponse\x12\x0f\n\x07verdict\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x15\n\rlp_locked_pct\x18\x03 \x01(\x01\x32\xcb\x01\n\x0e\x43hassisService\x12:\n\x0cGetPositions\x12\x0e.chassis.Empty\x1a\x1a.chassis.PositionsResponse\x12=\n\x0c\x45xecuteTrade\x12\x15.chassis.TradeRequest\x1a\x16.chassis.TradeResponse\x12>\n\rGetTokenAudit\x12\x15.chassis.AuditRequest\x1a\x16.chassis.AuditResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chassis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_TRADEREQUEST']._serialized_start=35
  _globals['_TRADEREQUEST']._serialized_end=103
  _globals['_TRADERESPONSE']._serialized_start=105
  _globals['_TRADERESPONSE']._serialized_end=179
  _globals['_POSITION']._serialized_start=181
  _globals['_POSITION']._serialized_end=272
  _globals['_POSITIONSRESPONSE']._serialized_start=274
  _globals['_POSITIONSRESPONSE']._serialized_end=331
  _globals['_AUDITREQUEST']._serialized_start=333
  _globals['_AUDITREQUEST']._serialized_end=367
  _globals['_AUDITRESPONSE']._serialized_start=369
  _globals['_AUDITRESPONSE']._serialized_end=439
  _globals['_CHASSISSERVICE']._serialized_start=442
  _globals['_CHASSISSERVICE']._serialized_end=645
# @@protoc_insertion_point(module_scope)
