# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chassis_pb2 as chassis__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chassis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChassisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPositions = channel.unary_unary(
                '/chassis.ChassisService/GetPositions',
                request_serializer=chassis__pb2.Empty.SerializeToString,
                response_deserializer=chassis__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.ExecuteTrade = channel.unary_unary(
                '/chassis.ChassisService/ExecuteTrade',
                request_serializer=chassis__pb2.TradeRequest.SerializeToString,
                response_deserializer=chassis__pb2.TradeResponse.FromString,
                _registered_method=True)
        self.GetTokenAudit = channel.unary_unary(
                '/chassis.ChassisService/GetTokenAudit',
                request_serializer=chassis__pb2.AuditRequest.SerializeToString,
                response_deserializer=chassis__pb2.AuditResponse.FromString,
                _registered_method=True)


class ChassisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPositions(self, request, context):
        """Monitoreo de posiciones
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTrade(self, request, context):
        """Control de trading
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenAudit(self, request, context):
        """Auditoría instantánea
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChassisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=chassis__pb2.Empty.FromString,
                    response_serializer=chassis__pb2.PositionsResponse.SerializeToString,
            ),
            'ExecuteTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTrade,
                    request_deserializer=chassis__pb2.TradeRequest.FromString,
                    response_serializer=chassis__pb2.TradeResponse.SerializeToString,
            ),
            'GetTokenAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenAudit,
                    request_deserializer=chassis__pb2.AuditRequest.FromString,
                    response_serializer=chassis__pb2.AuditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chassis.ChassisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chassis.ChassisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChassisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chassis.ChassisService/GetPositions',
            chassis__pb2.Empty.SerializeToString,
            chassis__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chassis.ChassisService/ExecuteTrade',
            chassis__pb2.TradeRequest.SerializeToString,
            chassis__pb2.TradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chassis.ChassisService/GetTokenAudit',
            chassis__pb2.AuditRequest.SerializeToString,
            chassis__pb2.AuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
